In [5]:
import numpy as np

In [10]:
x = np.random.randint(10,size = (8,3,2))
x

array([[[8, 2],
        [8, 5],
        [3, 8]],

       [[8, 5],
        [8, 4],
        [7, 6]],

       [[4, 0],
        [0, 7],
        [1, 8]],

       [[7, 9],
        [9, 3],
        [4, 4]],

       [[3, 2],
        [4, 7],
        [7, 1]],

       [[2, 5],
        [2, 8],
        [4, 0]],

       [[7, 9],
        [2, 4],
        [7, 1]],

       [[3, 9],
        [6, 9],
        [0, 0]]])

In [31]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [32]:
x.shape
x.dtype
x.ndim
x.itemsize
x.size
x.nbytes

(8, 3, 2)

dtype(&#39;int32&#39;)

3

4

48

192

In [34]:
x1 = np.arange(10)

In [35]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x1[:5]

array([0, 1, 2, 3, 4])

In [38]:
x1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [40]:
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
print(np.__version__)

1.19.2


## How to create a 1D array?

In [44]:
X2 = np.arange(10)
X2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

In [45]:
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Extract all odd numbers from array

In [48]:
arr = np.arange(10)
#Option1
arr[1::2]
#Option2
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

##  Replace all odd numbers in arr with -1

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[arr % 2 == 1] = -1

In [52]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [53]:
arr[arr % 2 == 1]

array([-1, -1, -1, -1, -1])

## How to replace items that satisfy a condition without affecting the original array?

In [59]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
out1 = np.where(arr%2 == 1,-1, arr)

In [63]:
out1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

## How to reshape an array?

In [67]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr.reshape(2,-1) #Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## How to stack two arrays vertically?

In [72]:
a = np.arange(10). reshape(2,-1)
b= np.repeat(1,10).reshape(2,-1)
a
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
#METHOD 1
np.concatenate([a,b], axis = 0)

#METHOD 2
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## How to stack two arrays horizontally?

In [76]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10). reshape(2,-1)

In [77]:
#METHOD 1
np.concatenate([a,b], axis = 1)

#METHOD 2
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## How to generate custom sequences in numpy without hardcoding?

In [19]:
import numpy as np

In [20]:
a = np.array([1,2,3])

In [26]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## How to get the common items between two python numpy arrays?

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [32]:
np.intersect1d(a,b)

array([2, 4])

## How to remove from one array those items that exist in another?

In [35]:
a = np.array([1,2,3,4,5])
b = ([5,6,7,8,9])

In [38]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

## How to get the positions where elements of two arrays match?

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

## How to extract all numbers between a given range from a numpy array?

In [47]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [51]:
#Get all items between 5 and 10 from a.
index = np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

In [53]:
(a >= 5) & (a <= 10)

array([False,  True, False,  True,  True, False, False])

## How to make a python function that handles scalars to work on numpy arrays?

In [57]:
def maxx(x,y):
    """Get Maximum of two Items"""
    if x >= y:
        return x
    else:
        return y

In [66]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(max, otypes=[int])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

## How to swap two columns in a 2d numpy array?

In [70]:
arr = np.arange(9).reshape(3,3)

In [71]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## How to reverse the rows of a 2D array?

In [3]:
import numpy as np
arr = np.arange(9).reshape(3,3)

In [5]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## How to create a 2D array containing random floats between 5 and 10?

In [12]:
arr = np.random.randint(low = 5, high = 10, size = (5,3))
arr

array([[5, 7, 7],
       [6, 8, 6],
       [8, 6, 6],
       [9, 8, 8],
       [5, 5, 6]])

In [15]:
rand_arr = np.random.uniform(5, 10, size = (5,3))
rand_arr

array([[8.12946104, 5.24874616, 5.36746396],
       [9.62798236, 6.34015886, 7.90226681],
       [5.82534548, 8.88043319, 8.97541504],
       [6.4233393 , 5.55344771, 5.70478502],
       [8.80330843, 6.68372403, 7.53181562]])

## How to print only 3 decimal places in python numpy array?

In [24]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.528, 0.248, 0.656],
       [0.203, 0.772, 0.991],
       [0.859, 0.533, 0.158],
       [0.891, 0.507, 0.411],
       [0.494, 0.522, 0.186]])

In [25]:
np.set_printoptions(precision = 3)

In [26]:
rand_arr

array([[0.528, 0.248, 0.656],
       [0.203, 0.772, 0.991],
       [0.859, 0.533, 0.158],
       [0.891, 0.507, 0.411],
       [0.494, 0.522, 0.186]])

In [28]:
rand_arr1 = np.random.random((5,3))
rand_arr1

array([[0.44 , 0.601, 0.181],
       [0.282, 0.171, 0.111],
       [0.817, 0.034, 0.921],
       [0.693, 0.695, 0.019],
       [0.027, 0.113, 0.444]])

## How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [33]:
np.random.seed(100)
arr = np.random.random([3,3])/1e3

In [34]:
arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [38]:
np.set_printoptions(suppress= True, precision = 6)

In [39]:
arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

## How to limit the number of items printed in output of numpy array?

In [41]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
np.set_printoptions(threshold=6)

In [43]:
a

array([ 0,  1,  2, ..., 17, 18, 19])

## How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [52]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

## How to extract a particular column from 1D array of tuples?

In [54]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url,delimiter=',', dtype = None)
iris_1d

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , b'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, b'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, b'Iris-virginica')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [59]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

## How to convert a 1d array of tuples to a 2d numpy array?

In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

In [6]:
iris_1d = np.genfromtxt(url, delimiter=',', dtype='object')
iris_1d[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa']], dtype=object)

In [62]:
iris_1d

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , b'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, b'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, b'Iris-virginica')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [63]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [69]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

## How to compute the mean, median, standard deviation of a numpy array?

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',',dtype=object)
sepallength = np.genfromtxt(url,delimiter=',', dtype=float, usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [19]:
iris[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa']], dtype=object)

In [27]:
mean, median, standard_deviation = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, median, standard_deviation)

5.843333333333334 5.8 0.8253012917851409


## How to normalize an array so the values range exactly between 0 and 1?

In [34]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',',dtype=float,usecols=[0])

Smax, Smin = np.max(sepallength), np.min(sepallength)
S = (sepallength-Smin)/(Smax-Smin)
np.set_printoptions(precision=3)
print(S)

[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


## How to compute the softmax score?

In [39]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=object)

sepallength = np.array([float(row[0]) for row in iris])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [40]:
def softmax(x):
    e_x = np.exp(x-np.max(x))
    return e_x/e_x.sum(axis = 0)

In [41]:
print(softmax(sepallength))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


## How to find the percentile scores of a numpy array?

In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype=float, usecols=[0])

In [46]:
np.percentile(sepallength,q=[5,25,50,75,95])

array([4.6  , 5.1  , 5.8  , 6.4  , 7.255])

## How to insert values at random positions in an array?
## Insert np.nan values at 20 random positions in iris_2d dataset

In [52]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype=object)

i, j = np.where(iris_2d)
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan


## How to find the position of missing values in numpy array?

In [ ]:
#Find the number and position of missing values in iris_2d's sepallength (1st column)


In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))


Number of missing values: 
 8
Position of missing values: 
 (array([  6,   9,  16,  35,  39,  51, 121, 122], dtype=int32),)


In [56]:
np.random.randint(4, size=20)

array([0, 3, 2, 1, 3, 0, 1, 2, 2, 2, 2, 0, 2, 3, 2, 3, 1, 0, 2, 2])

In [57]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo